server:
  port: 8090

logging:
  file:
    path: server.log

spring:
  application:
    name: MyTest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/course?serverTimezone=CST
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*

